#!/usr/bin/env bash
# Change your home IP

# Cambiar localhost a 127.0.0.2
sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost$/127.0.0.2 localhost/' /etc/hosts

# Cambiar o agregar facebook.com
if grep -q "facebook.com" /etc/hosts
then
    sed -i 's/^.*facebook\.com$/8.8.8.8 facebook.com/' /etc/hosts
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
